// Update this file to control sidebar navigation per permission.

import {
  LayoutDashboard,
  ShoppingCart,
  ShoppingBag,
  Package,
  Users,
  Settings,
  Truck,
  BarChart2,
  DollarSign,
  ClipboardList,
  FileText,
  Tag,
  UserCheck,
  Shield,
  Activity,
  CreditCard,
  AlertTriangle,
  RotateCcw,
  Layers,
  Smartphone,
  Bell,
  Printer,
  Percent,
  Hash,
  Boxes,
  Archive,
  Store,
  Briefcase,
  Image as ImageIcon,
  Box,
} from 'lucide-react';
import type { RoleType } from '@/features/auth/types';

export interface NavItem {
  name: string;
  href: string;
  icon: React.ElementType;
  badge?: string;
  roles?: RoleType[]; // deprecated: left for backwards compatibility
  permission?: string; // New permission key
  children?: NavItem[];
}

export interface NavGroup {
  group: string;
  items: NavItem[];
}

export const NAV_GROUPS: NavGroup[] = [
  {
    group: 'Tổng quan',
    items: [
      { name: 'Dashboard', href: '/', icon: LayoutDashboard },
    ],
  },
  {
    group: 'Bán hàng (POS)',
    items: [
      { name: 'Màn hình POS', href: '/pos', icon: ShoppingCart, permission: 'pos:access' },
      { name: 'Ca làm việc POS', href: '/pos/sessions', icon: Activity, permission: 'pos:sessions:view' },
      { name: 'Phương thức TT', href: '/pos/payment-methods', icon: CreditCard, permission: 'pos:payments:manage' },
    ],
  },
  {
    group: 'Quản lý Đơn hàng',
    items: [
      { name: 'Đơn bán hàng', href: '/sales', icon: ShoppingBag, permission: 'sales:orders:view' },
      { name: 'Đơn hàng Online', href: '/sales/online', icon: ShoppingBag, permission: 'sales:orders:view' },
      { name: 'Báo giá', href: '/sales/quotes', icon: FileText, permission: 'sales:quotes:manage' },
      { name: 'Xuất Hóa đơn', href: '/sales/invoices', icon: ClipboardList, permission: 'sales:invoices:manage' },
      { name: 'Khách trả hàng', href: '/sales/returns', icon: RotateCcw, permission: 'sales:returns:manage' },
      { name: 'Khảo sát báo giá', href: '/sales/offers', icon: FileText, permission: 'sales:quotes:manage' },
      { name: 'Hóa đơn bán lẻ', href: '/sales/invoices-list', icon: ClipboardList, permission: 'sales:invoices:manage' },
      { name: 'Thanh toán khách', href: '/sales/payments', icon: CreditCard, permission: 'sales:invoices:manage' },
      { name: 'Công nợ Phải thu', href: '/sales/receivables', icon: DollarSign, permission: 'sales:orders:view' },
      { name: 'Danh sách Hóa đơn', href: '/sales/invoice-lists', icon: FileText, permission: 'sales:invoices:manage' },
      { name: 'Phiếu xuất giao hàng', href: '/sales/delivery-lists', icon: Truck, permission: 'sales:orders:view' },
      { name: 'Biên bản Giao nhận', href: '/sales/delivery-notes', icon: FileText, permission: 'sales:orders:view' },
      { name: 'Yêu cầu trả hàng', href: '/sales/returns-list', icon: RotateCcw, permission: 'sales:returns:manage' },
      { name: 'Lịch sử khách trả', href: '/sales/returns-history', icon: RotateCcw, permission: 'sales:returns:manage' },
      { name: 'Đơn sale đi tuyến', href: '/sales/market-orders', icon: ShoppingBag, permission: 'sales:orders:view' },
    ],
  },
  {
    group: 'Quản lý Kho',
    items: [
      { name: 'Danh sách Sản phẩm', href: '/inventory', icon: Package, permission: 'inventory:products:view' },
      { name: 'Lô hàng', href: '/inventory/batches', icon: Archive, permission: 'inventory:ledger:view' },
      { name: 'Số Serial', href: '/inventory/serials', icon: Hash, permission: 'inventory:products:view' },
      { name: 'Combo Sản phẩm', href: '/inventory/combos', icon: Boxes, permission: 'inventory:products:view' },
      { name: 'Chuyển kho', href: '/inventory/transfers', icon: Truck, permission: 'inventory:transfers:manage' },
      { name: 'Kiểm kê kho', href: '/inventory/checks', icon: ClipboardList, permission: 'inventory:checks:manage' },
      { name: 'Phiếu Nhập kho', href: '/inventory/imports', icon: Layers, permission: 'inventory:imports:manage' },
      { name: 'Trả hàng NCC', href: '/inventory/returns', icon: RotateCcw, permission: 'inventory:returns:manage' },
      { name: 'Hủy hàng', href: '/inventory/cancel', icon: AlertTriangle, permission: 'inventory:writeoff:manage' },
      { name: 'Thẻ kho', href: '/inventory/ledger', icon: Activity, permission: 'inventory:ledger:view' },
      { name: 'Danh mục', href: '/inventory/categories', icon: Tag, permission: 'inventory:categories:manage' },
      { name: 'Đơn vị tính', href: '/inventory/units', icon: Layers, permission: 'inventory:categories:manage' },
      { name: 'Xem trên Mobile', href: '/inventory/mobile', icon: Smartphone, permission: 'inventory:products:view' },
      { name: 'Kiểm kê mã vạch', href: '/inventory/stock-keeping', icon: Hash, permission: 'inventory:products:view' },
      { name: 'Yêu cầu xuất kho', href: '/inventory/stock-outs', icon: Truck, permission: 'inventory:transfers:manage' },
      { name: 'Phiếu điều chỉnh tồn', href: '/inventory/adjustments', icon: ClipboardList, permission: 'inventory:checks:manage' },
      { name: 'Chi tiết sản phẩm kho', href: '/inventory/details', icon: Package, permission: 'inventory:products:view' },
      { name: 'Dashboard tồn kho', href: '/inventory/dashboard', icon: LayoutDashboard, permission: 'inventory:ledger:view' },
      { name: 'Hàng hoá trong kho', href: '/inventory/product-storages', icon: Layers, permission: 'inventory:products:view' },
      { name: 'Tồn kho chi nhánh', href: '/inventory/product-warehouses', icon: Store, permission: 'inventory:products:view' },
      { name: 'Sản phẩm NCC cấp', href: '/inventory/supplier-products', icon: UserCheck, permission: 'inventory:products:view' },
      { name: 'Kho bãi NCC cấp', href: '/inventory/supplier-storages', icon: Layers, permission: 'inventory:products:view' },
      { name: 'Nhà kho NCC cấp', href: '/inventory/supplier-warehouses', icon: Store, permission: 'inventory:products:view' },
      { name: 'Khu vực lưu trữ', href: '/inventory/storage-areas', icon: Archive, permission: 'inventory:categories:manage' },
      { name: 'Vị trí kho hàng', href: '/inventory/warehouse-areas', icon: Store, permission: 'inventory:categories:manage' },
      { name: 'Phân khu kho bãi', href: '/inventory/warehouse-zones', icon: Store, permission: 'inventory:categories:manage' },
      { name: 'Vị trí ô kệ kệ hàng', href: '/inventory/warehouse-bins', icon: Layers, permission: 'inventory:categories:manage' },
      { name: 'Phiếu chuyển kho', href: '/inventory/transfers-list', icon: Truck, permission: 'inventory:transfers:manage' },
      { name: 'Yêu cầu chuyển hàng', href: '/inventory/transfer-requests', icon: Truck, permission: 'inventory:transfers:manage' },
    ],
  },
  {
    group: 'Mua hàng',
    items: [
      { name: 'Nhà cung cấp', href: '/purchase/suppliers', icon: UserCheck, permission: 'purchase:suppliers:manage' },
      { name: 'Đơn mua hàng', href: '/purchase/orders', icon: ShoppingBag, permission: 'purchase:orders:manage' },
      { name: 'Đề xuất Mua hàng', href: '/purchase/requests', icon: FileText, permission: 'purchase:orders:manage' },
      { name: 'Hợp đồng NCC', href: '/purchase/contracts', icon: ClipboardList, permission: 'purchase:suppliers:manage' },
      { name: 'Đánh giá NCC', href: '/purchase/evaluations', icon: UserCheck, permission: 'purchase:suppliers:manage' },
      { name: 'Lịch sử nhận hàng', href: '/purchase/deliveries', icon: Truck, permission: 'purchase:orders:manage' },
      { name: 'Hóa đơn Mua hàng', href: '/purchase/invoices', icon: ClipboardList, permission: 'purchase:orders:manage' },
      { name: 'Thanh toán NCC', href: '/purchase/payments', icon: DollarSign, permission: 'purchase:orders:manage' },
      { name: 'Phiếu trả hàng NCC', href: '/purchase/returns-list', icon: RotateCcw, permission: 'purchase:orders:manage' },
      { name: 'Lịch sử trả hàng NCC', href: '/purchase/returns-history', icon: RotateCcw, permission: 'purchase:orders:manage' },
      { name: 'Yêu cầu báo giá NCC', href: '/purchase/supplier-requests', icon: FileText, permission: 'purchase:orders:manage' },
    ],
  },
  {
    group: 'Kế toán & Tài chính',
    items: [
      { name: 'Phiếu thu', href: '/finance/receipts', icon: DollarSign, permission: 'finance:receipts:manage' },
      { name: 'Phiếu chi', href: '/finance/payments', icon: DollarSign, permission: 'finance:payments:manage' },
      { name: 'Sổ nợ', href: '/finance/debts', icon: Activity, permission: 'finance:debts:view' },
      { name: 'Chi phí vận hành', href: '/finance/costs', icon: BarChart2, permission: 'finance:costs:manage' },
      { name: 'Tài khoản Ngân hàng', href: '/finance/banks', icon: CreditCard, permission: 'finance:banks:manage' },
      { name: 'Sổ nhật ký', href: '/finance/journal', icon: FileText, permission: 'finance:journal:manage' },
      { name: 'Lý do giao dịch', href: '/finance/transaction-reasons', icon: ClipboardList, permission: 'finance:reasons:manage' },
      { name: 'Nghĩa vụ thuế', href: '/finance/tax-duties', icon: FileText, permission: 'finance:journal:manage' },
      { name: 'Chốt số dư quỹ', href: '/finance/fund-balances', icon: DollarSign, permission: 'finance:journal:manage' },
      { name: 'Tài khoản kế toán', href: '/finance/chart-of-accounts', icon: Layers, permission: 'finance:journal:manage' },
      { name: 'Tài sản cố định', href: '/finance/fixed-assets', icon: Archive, permission: 'finance:journal:manage' },
      { name: 'Trung tâm chi phí', href: '/finance/cost-centers', icon: BarChart2, permission: 'finance:costs:manage' },
    ],
  },
  {
    group: 'Khách hàng (CRM)',
    items: [
      { name: 'Khách hàng', href: '/crm', icon: Users, permission: 'crm:customers:manage' },
      { name: 'Hạng thành viên', href: '/crm/tiers', icon: Tag, permission: 'crm:loyalty:manage' },
      { name: 'Voucher', href: '/crm/vouchers', icon: Tag, permission: 'crm:vouchers:manage' },
      { name: 'Phản hồi', href: '/crm/feedback', icon: Activity, permission: 'crm:feedback:manage' },
      { name: 'Hỗ trợ Tickets', href: '/crm/tickets', icon: AlertTriangle, permission: 'crm:feedback:manage' },
      { name: 'Ví Voucher khách', href: '/crm/customer-vouchers', icon: Tag, permission: 'crm:vouchers:manage' },
      { name: 'Sổ bảo hành sản phẩm', href: '/crm/warranties', icon: FileText, permission: 'crm:warranties:manage' },
      { name: 'Yêu cầu bảo hành', href: '/crm/warranty-claims', icon: AlertTriangle, permission: 'crm:warranty-claims:manage' },
      { name: 'Nhóm Đối tác', href: '/crm/partner-groups', icon: Users, permission: 'crm:customers:manage' },
      { name: 'Khu vực địa lý', href: '/crm/areas', icon: Store, permission: 'crm:customers:manage' },
      { name: 'Lịch sử tích/tiêu điểm', href: '/crm/loyalty-history', icon: Activity, permission: 'crm:loyalty:manage' },
      { name: 'Chiến dịch Marketing', href: '/crm/campaigns', icon: Tag, permission: 'crm:vouchers:manage' },
    ],
  },
  {
    group: 'Vận chuyển & Logistics',
    items: [
      { name: 'Đối tác giao hàng', href: '/logistics/shippers', icon: Truck, permission: 'logistics:shippers:manage' },
      { name: 'Chuyến xe', href: '/logistics/trips', icon: Truck, permission: 'logistics:trips:manage' },
      { name: 'Bảng giá', href: '/logistics/prices', icon: Tag, permission: 'logistics:prices:manage' },
      { name: 'Khuyến mãi', href: '/logistics/promotions', icon: Tag, permission: 'logistics:prices:manage' },
      { name: 'Đối tác vận chuyển', href: '/logistics/carriers', icon: Truck, permission: 'logistics:shippers:manage' },
      { name: 'Phương thức vận chuyển', href: '/logistics/methods', icon: Truck, permission: 'logistics:shippers:manage' },
      { name: 'Cước phí vận chuyển', href: '/logistics/charges', icon: DollarSign, permission: 'logistics:shippers:manage' },
      { name: 'Biểu phí giao hàng', href: '/logistics/fees', icon: DollarSign, permission: 'logistics:shippers:manage' },
      { name: 'Tỷ lệ cước phí', href: '/logistics/fee-rates', icon: DollarSign, permission: 'logistics:shippers:manage' },
      { name: 'Nhóm biểu phí', href: '/logistics/fee-groups', icon: Layers, permission: 'logistics:shippers:manage' },
      { name: 'Lô hàng vận chuyển', href: '/logistics/shipments', icon: Truck, permission: 'logistics:trips:manage' },
      { name: 'Ghi chú vận chuyển', href: '/logistics/notes', icon: FileText, permission: 'logistics:trips:manage' },
      { name: 'Đơn vận chuyển', href: '/logistics/orders', icon: FileText, permission: 'logistics:trips:manage' },
      { name: 'Khu vực giao hàng', href: '/logistics/locations', icon: Store, permission: 'logistics:shippers:manage' },
      { name: 'Danh bạ vận chuyển', href: '/logistics/contacts', icon: Users, permission: 'logistics:shippers:manage' },
      { name: 'Địa chỉ giao hàng', href: '/logistics/addresses', icon: Store, permission: 'logistics:shippers:manage' },
      { name: 'Lô đơn vận chuyển', href: '/logistics/batches', icon: Layers, permission: 'logistics:trips:manage' },
      { name: 'Phiếu đóng gói', href: '/logistics/packing-lists', icon: Box, permission: 'logistics:trips:manage' },
      { name: 'Biên bản giao nhận hàng', href: '/logistics/delivery-notes', icon: FileText, permission: 'logistics:trips:manage' },
    ],
  },
  {
    group: 'Kênh bán (Omnichannel)',
    items: [
      { name: 'Kênh bán sàn TMĐT', href: '/omnichannel/channels', icon: Store, permission: 'system:settings:manage' },
      { name: 'Liên kết sản phẩm sàn', href: '/omnichannel/mappings', icon: Layers, permission: 'system:settings:manage' },
      { name: 'Nhật ký Webhook', href: '/omnichannel/webhook-logs', icon: Activity, permission: 'system:settings:manage' },
    ],
  },
  {
    group: 'Báo cáo',
    items: [
      { name: 'Báo cáo Bán hàng', href: '/reports/sales', icon: BarChart2, permission: 'sales:orders:view' },
      { name: 'Báo cáo Tồn kho', href: '/reports/inventory', icon: BarChart2, permission: 'inventory:ledger:view' },
      { name: 'Báo cáo Tài chính', href: '/reports/finance', icon: BarChart2, permission: 'finance:debts:view' },
      { name: 'Báo cáo CRM', href: '/reports/crm', icon: BarChart2, permission: 'crm:customers:manage' },
    ],
  },
  {
    group: 'Hệ thống',
    items: [
      { name: 'Quản lý Chi nhánh', href: '/system/branches', icon: Store, permission: 'system:settings:manage' },
      { name: 'Nhân viên', href: '/hr/users', icon: Users, permission: 'admin:users:manage' },
      { name: 'Phân quyền', href: '/hr/roles', icon: Shield, permission: 'admin:roles:manage' },
      { name: 'Phòng ban', href: '/hr/departments', icon: Users, permission: 'admin:departments:manage' },
      { name: 'Chức danh', href: '/hr/positions', icon: Briefcase, permission: 'admin:positions:manage' },
      { name: 'Lịch sử hoạt động', href: '/hr/logs', icon: Activity, permission: 'admin:logs:view' },
      { name: 'Hợp đồng lao động', href: '/hr/contracts', icon: FileText, permission: 'admin:users:manage' },
      { name: 'Chấm công hàng ngày', href: '/hr/attendance', icon: UserCheck, permission: 'admin:users:manage' },
      { name: 'Đơn xin nghỉ phép', href: '/hr/leave-requests', icon: FileText, permission: 'admin:users:manage' },
      { name: 'Đánh giá KPI', href: '/hr/kpis', icon: Activity, permission: 'admin:users:manage' },
      { name: 'Bảng lương nhân sự', href: '/hr/payroll', icon: DollarSign, permission: 'admin:users:manage' },
      { name: 'Bảo mật quyền hệ thống', href: '/system/permissions', icon: Shield, permission: 'admin:roles:manage' },
      { name: 'Phiên đăng nhập thiết bị', href: '/system/device-sessions', icon: Smartphone, permission: 'system:settings:manage' },
      { name: 'Lịch sử đổi mật khẩu', href: '/system/password-history', icon: Activity, permission: 'system:settings:manage' },
      { name: 'Cài đặt chung', href: '/settings', icon: Settings, permission: 'system:settings:manage' },
      { name: 'Cấu hình Hệ thống', href: '/system/config', icon: Settings, permission: 'system:settings:manage' },
      { name: 'Cấu hình Thuế', href: '/system/vat', icon: Percent, permission: 'system:vat:manage' },
      { name: 'Mẫu in', href: '/system/templates', icon: Printer, permission: 'system:settings:manage' },
      { name: 'Quản lý Banner', href: '/system/banners', icon: ImageIcon, permission: 'system:settings:manage' },
      { name: 'Luật thông báo', href: '/system/notifications', icon: Bell, permission: 'system:settings:manage' },
      { name: 'Lịch sử lỗi', href: '/system/errors', icon: AlertTriangle, permission: 'system:errors:view' },
    ],
  },
];
